### ISSUE TITLE
Doesn't appear in guitarix

### ISSUE THREAD

**Issue by rcspam** [ssj71/infamousPlugins#1]
Hey ssj71,
Perhaps i had missing something but the infamous plugins doesn't appear in guitarix?

**Comment by ssj71** [comment]
There are several lv2 features that guitarix does not support, so it will not show plugins that require those features. I just used a template for all these plugins that requires all the same features. Many of the plugins don't actually require them so I will go through and remove those requirements for plugins that don't need those features.

**Comment by ssj71** [comment]
I have made the change already in the devel branch but it will be a little bit before I merge it into master. There are still several issues with devel I must resolve first. I will leave this open until it is merged to master

**Comment by rcspam** [comment]
Ok, thanks

**Comment by ssj71** [comment]
ok, this is resolved now. Thanks for the report!

**Comment by rcspam** [comment]
Sorry Spencer but after have compile it (with default install in /usr/local/lib64/lv2 and update LV2_PATH in .bashrc ), they appear only in ardour :) but nothing in carla (after set the lv2 path), nor in guitarix (i suppose this last use lv2ls to know all lv2 pluggins)

**Comment by rcspam** [comment]
Btw, carla doesn't find rkrlv2 plugins, so perhaps a bug in last kxstudio carla package ! ...

**Comment by ssj71** [comment]
If you are using kxstudio you should install to the default location of
/usr/local/lib/lv2 . let me know if that fixes it.

**Comment by rcspam** [comment]
No at home for now,  so i cant try, but i have put /urs/local/lib64/lv2 in
carla pref lv2 path... but i ll try.

**Comment by rcspam** [comment]
As I suspected, ther no change if i move infamous lv2 plugins in /usr/local/lib/lv2.
Btw, rkrlv2 was already here.. and do not appear in carla either.

**Comment by rcspam** [comment]
It's ok now, an old carla.conf deleted has resolve my problem.
For guitarix, i have remove my github compilled install and install the kxstudio one (ppa) and you know what ? It appears in.
So thanks and regards.

**Comment by ssj71** [comment]
great. Thanks for letting me know!
