### ISSUE TITLE
Cannot build without UI

### ISSUE THREAD

**Issue by falkTX** [ssj71/infamousPlugins#15]
I'm trying to build these plugins for MOD, which means no UI.
The build fails with stuff like this:

```
make[3]: *** No rule to make target `src/envfollower/FLTK_FLUID_EXECUTABLE-NOTFOUND', needed by `src/envfollower/envfollower_ui.h'.  Stop.
make[3]: *** No rule to make target `src/casynth/FLTK_FLUID_EXECUTABLE-NOTFOUND', needed by `src/casynth/casynth_ui.h'.  Stop.
```

**Comment by ssj71** [comment]
In the devel branch I've made a custom target called no-GUI. You can make this and it will generate the binaries you need into build/src/$plugin. If you try to install, it will try to build all, including the GUI stuff. I can add an install-no-GUI target maybe that installs them into a local folder or something. Would that be better?

 I was waiting to see if the no-GUI target would work for you before I merged it into master.

**Comment by ssj71** [comment]
alright, I added a way to install no-GUI, merged it to master and added instructions to the readme. Let me know if there's any issue remaining.

**Comment by falkTX** [comment]
This would usually be done automatically by cmake rules, but ok I'll see if I can make the current instructions work..

**Comment by ssj71** [comment]
I looked quite a bit on how to make cmake install everything by default but still have a method to build/install without the UI targets. This was the best solution I could come up with. If you can link me to a better one, I'd be happy to update.

**Comment by ssj71** [comment]
need to add ifs so that GUIs are only added if NTK is found.

**Comment by ssj71** [comment]
now done in the devel branch. Will merge to master for next release.
