### ISSUE TITLE
i tried to compile the infamousPlugins but get an error

### ISSUE THREAD

**Issue by Bigjuergo** [ssj71/infamousPlugins#26]
can you please help me?
why is it not possible to install from the software manager?
thank you anyway!

```
build # make
[  2%] Built target infamous-rule
make[2]: *** No rule to make target '../src/casynth/FLTK_FLUID_EXECUTABLE-NOTFOUND', needed by 'src/casynth/casynth_ui.h'.  Stop.
CMakeFiles/Makefile2:197: recipe for target 'src/casynth/CMakeFiles/casynth_ui.dir/all' failed
make[1]: *** [src/casynth/CMakeFiles/casynth_ui.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ssj71** [comment]
The build failed because you are missing the NTK dependency. But there's an easier way:
If you are on linux mint just install the KXStudio PPAs, they have the infamous plugins packaged there.
See http://kxstudio.linuxaudio.org/Repositories for instructions.
Once thats done you should be able to run "sudo apt-get install infamous-plugins"

If you'd like to build from source (there are some improvements since they were packaged) I can help you. The [readme](https://github.com/ssj71/infamousPlugins/blob/master/README) has instructions to help you install NTK as well. Let me know how it goes.

**Comment by Bigjuergo** [comment]
thank you for your answer!if i installed the KXStudio PPAs, i get following error:
Reading package lists... DoneBuilding dependency tree       Reading state information... DoneE: Unable to locate package infamous-plugins
the packet manager telles me that the repository was installed.if i look at the summary of plugins the brilliant infamous-plugins are not included.
 

    ssj71 <notifications@github.com> schrieb am 18:13 Montag, 12.Dezember 2016:
 

 The build failed because you are missing the NTK dependency. But there's an easier way:
If you are on linux mint just install the KXStudio PPAs, they have the infamous plugins packaged there.
See http://kxstudio.linuxaudio.org/Repositories for instructions.
Once thats done you should be able to run "sudo apt-get install infamous-plugins"If you'd like to build from source (there are some improvements since they were packaged) I can help you. The readme has instructions to help you install NTK as well. Let me know how it goes.—

**Comment by ssj71** [comment]
Try to run another "sudo apt-get update" after you've installed the ppa.

**Comment by Bigjuergo** [comment]
wow it is so easy when you know how -> THANK YOU VERY MUCH!!!
 

    ssj71 <notifications@github.com> schrieb am 18:42 Montag, 12.Dezember 2016:
 

 Try to run another "sudo apt-get update" after you've installed the ppa.—

**Comment by ssj71** [comment]
you're welcome! If you are having other problems with linux audio in general, I encourage you to join us at the linuxmusicians.com forums. Lots of help to be had there. :)

oh and you are welcome to ask specifics about how to use the infamous plugins there too, the info will be seen by more people there and help more people. For technical issues though, this is the right place to post, so thanks for contacting me!
