### ISSUE TITLE
lushlife and envelopper follower (CV) not working

### ISSUE THREAD

**Issue by trebmuh** [ssj71/infamousPlugins#28]
Debian Jessie up to date here. Infamous build from current master branch.

```
$ jalv.qt http://ssj71.github.io/infamousPlugins/plugs.html#lushlife
Plugin:       http://ssj71.github.io/infamousPlugins/plugs.html#lushlife
UI:           http://ssj71.github.io/infamousPlugins/plugs.html#lushlife_ui
JACK Name:    the infamous lush life
Block length: 128 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25,0 Hz

LATENCY    = 0,000000
MASTERGAIN = 1,000000
DRYGAIN    = 0,500000
DRYPAN     = 0,000000
LFOSHAPE   = 0,700000
LFOSYNC    = 0,000000
ACTIVE0    = 1,000000
DETUNE0    = 0,001000
DTLFOAMT0  = 0,050000
DTLFOFREQ0 = 0,300000
DELAY0     = 10,000000
DLLFOAMT0  = 10,000000
DLLFOFREQ0 = 0,600000
GAIN0      = 0,500000
PAN0       = 0,000000
ACTIVE1    = 0,000000
DETUNE1    = -0,100000
DTLFOAMT1  = 0,100000
DTLFOFREQ1 = 0,550000
DELAY1     = 70,000000
DLLFOAMT1  = 1,000000
DLLFOFREQ1 = 0,000000
GAIN1      = 0,800000
PAN1       = -0,500000
ACTIVE2    = 0,000000
DETUNE2    = 0,200000
DTLFOAMT2  = 0,100000
DTLFOFREQ2 = 0,000000
DELAY2     = 110,000000
DLLFOAMT2  = 1,000000
DLLFOFREQ2 = 0,000000
GAIN2      = 0,400000
PAN2       = 0,900000
ACTIVE3    = 0,000000
DETUNE3    = -0,200000
DTLFOAMT3  = 0,100000
DTLFOFREQ3 = 0,000000
DELAY3     = 120,000000
DLLFOAMT3  = 1,000000
DLLFOFREQ3 = 0,000000
GAIN3      = 0,400000
PAN3       = -0,900000
ACTIVE4    = 0,000000
DETUNE4    = 0,050000
DTLFOAMT4  = 0,100000
DTLFOFREQ4 = 0,000000
DELAY4     = 40,000000
DLLFOAMT4  = 1,000000
DLLFOFREQ4 = 0,000000
GAIN4      = 0,300000
PAN4       = 0,200000
ACTIVE5    = 0,000000
DETUNE5    = -0,050000
DTLFOAMT5  = 0,100000
DTLFOFREQ5 = 0,000000
DELAY5     = 30,000000
DLLFOAMT5  = 1,000000
DLLFOFREQ5 = 0,000000
GAIN5      = 0,300000
PAN5       = -0,200000
Preset: http://ssj71.github.io/infamousPlugins/plugs.html#lushlife:preset:05bluebellchoir
Preset: http://ssj71.github.io/infamousPlugins/plugs.html#lushlife:preset:00Dfault
Preset: http://ssj71.github.io/infamousPlugins/plugs.html#lushlife:preset:01Stereo
Preset: http://ssj71.github.io/infamousPlugins/plugs.html#lushlife:preset:02PingPongPitch
Preset: http://ssj71.github.io/infamousPlugins/plugs.html#lushlife:preset:03TightChoir
Preset: http://ssj71.github.io/infamousPlugins/plugs.html#lushlife:preset:04Lush
Segfault
```

```
$ jalv.qt http://ssj71.github.io/infamousPlugins/plugs.html#envfollowerCV
Plugin:       http://ssj71.github.io/infamousPlugins/plugs.html#envfollowerCV
UI:           http://ssj71.github.io/infamousPlugins/plugs.html#envfollowerCV_ui
Mandatory port has unknown data type
```

Any hint?

**Comment by ssj71** [comment]
sorry for the delay. I finally got a chance to look at this last night.
These are 2 separate issues.
I unfortunately could not reproduce the issue with lushlife. Are you able to run it with gdb and get me a backtrace? That would be very helpful. I wonder if it may be something with ntk. At least try to run it in jalv with the -g option to use the generic UI and see if it still segfaults. Its got to be some difference in one of the dep libs between your system and mine. Lushlife also uses the zita-resampler.

With envfollowerCV you can't use it in jalv because jalv lacks CV support. I think CVs are only useable in ingen at this time, unfortunately, but for ingen users it's much better than the midi version.

**Comment by trebmuh** [comment]
OK. I've been building Ingen today and the envelope follower (CV) is loading fine. Thanks for the hint.

For lushlife, as said on IRC, I'll build another version of the infamous-plugins (not in a debian pbuilder chroot this time) and check that makes a difference, including the fact to get debug symbols activated in order to report much more information to you.

to be continued...

**Comment by ssj71** [comment]
great thanks for the feedback and the help!

**Comment by ssj71** [comment]
does this issue still exist?

**Comment by trebmuh** [comment]
Hell, I totally forgot about this issue. Unfortunately, I'll not have time those days to test it again. I'll update here as soon as I'll have some new, but feel free to close it if you think that's better.

**Comment by trebmuh** [comment]
Apologize for a thatttttttt lllllllong delay in answering. I forgot (a second time) this issue.
I'm now on Debian stretch (up-to-date), and lushlife is still segfaulting when launched with: `jalv.gtk http://ssj71.github.io/infamousPlugins/plugs.html#lushlife`. Same with `jalv.gtk -g http://ssj71.github.io/infamousPlugins/plugs.html#lushlife`.

I'll try to find some time to build a -debug version and provides you with a gdb trace.

**Comment by ssj71** [comment]
I think this issue has been happening to other people, but unfortunately I have not been able to reproduce it on my ubuntu 16.04 or my ubuntu 14.04 versions. A backtrace would help a lot!
No worries about the delay, I kinda forgot too since I CNR.

**Comment by trebmuh** [comment]
Hi @ssj71 , I've been looking around in the doc and source for how to build a debug version but am not too sure how to do so.

I've build a binary doing `cmake`, then `make --debug`, but (here too), I'm not too sure if that's the right way.

Would you mind giving me the magics in order to build a debug version correctly and run it through gdb?

**Comment by ssj71** [comment]
actually, anything built from source will be debug unless you edit the cmake configs. I just make it add the debug flags by default.

**Comment by ssj71** [comment]
I have finally fixed this! Thanks for the report. You can use the latest release and lushlife should work better (and faster) than ever. https://github.com/ssj71/infamousPlugins/releases/tag/v0.2.03

**Comment by trebmuh** [comment]
nice @ssj71 .

I've been building the 0.2.03 version and have tested lush life which works, Congratulations for finding the culprit and thanks !
