### ISSUE TITLE
The last commits seems to break the Zynthian build

### ISSUE THREAD

**Issue by jofemodo** [ssj71/infamousPlugins#35]
https://jenkins.zynthian.org/job/ZynthianOS/464/parsed_console/

**Comment by ssj71** [comment]
thanks for the report! I'll look into it ASAP. I was trying to quickly merge and release a couple years worth of little fixes and something must have broken.

**Comment by Joermungand** [comment]
Same here, on Arch. Going back through the commit history, it seems the error actually appears with commit c93c044e854ba22a9e0200698864134d0b356283, dated February 12th.

**Comment by ssj71** [comment]
its resolved on my system now, please try again, sorry for the issues.

**Comment by ssj71** [comment]
@Joermungand actually I don't see that issue. Can you paste the output of `make VERBOSE=1`? It may be a separate issue.

**Comment by Joermungand** [comment]
Never mind, it builds perfectly fine after the latest commit. Thanks a lot!

**Comment by ssj71** [comment]
great, thanks.
@jofemodo we'll see that the build completes successfully tonight and then close this (or figure out what the next fix will need).

**Comment by jofemodo** [comment]
Nice ;-)

**Comment by ssj71** [comment]
Build looks green again. \o/ I'm closing this. Thanks again for bringing it up quickly.

**Comment by jofemodo** [comment]
Thanks! Confirmed It works again ;-)
