### ISSUE TITLE
[Mindi] Pitch wheel/bend messages (msgtype 14) incorrectly converted into SYSEX messages (msgtype 15)

### ISSUE THREAD

**Issue by ericfont** [ssj71/infamousPlugins#44]
In the process of fixing momentary messages, when testing the LV2 plugin inside Carla host, I discovered that the pitchwheel messages (msgtype 14) always incorrectly get converted to SYSEX messages (msgtype 15).

After investigating, the error seems to result from the mindi.ttl port definition for MSGTYPE having "lv2:maximum 15", and that changing that to "lv2:maximum 14" produces the desired behavior.

I suspect this is a quirk with how lv2 implements "scalepoint" conversion when converting from a list of integer values to a floating point value, though I'm not sure cause I'm not familiar with the implementation.

I will include this fix as a separate commit in my upcoming PR for mindi.

**Comment by ssj71** [comment]
Hmm, this issue I think is a carla specific one. Can you test with jalv or Ardour? I would like to support systex messages because I have some midi utilities that I test using mindi.

**Comment by ericfont** [comment]
interesting.  Testing in Ardour, and I see that it msgtype 14 is interpreted correctly as pitchwheel/bend.  So I guess the issue for that is Carla.

**Comment by ericfont** [comment]
and I see in jalv also that msgtype 14 works correclty as pitchwheel/bend.  So this is really Carla at fault.

**Comment by ericfont** [comment]
I'll undo that change of the minimum, in that case.  It seems I'll have to tell carla about this.

I guess to support SYSEX messages, will need another parameter which is basically a list of bytes to send.
