### ISSUE TITLE
[Mindi] Channel pressure/aftertouch (msgtype 13) should really use DATA2 ("Value") for value, not DATA1 ("Note/CC/PG Number")

### ISSUE THREAD

**Issue by ericfont** [ssj71/infamousPlugins#45]
In investigating fixing up the momentary feature, I discovered a separate issue that Midi message 13 (Channel Pressure aka Channel aftertouch) was using DATA1 ("Note/CC/PG Number") for the midi message's value, when it should really more appropriately use DATA2 ("Value").  The midi specs https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message does use value "vvvvvvv"
![midi-format-pressure](https://user-images.githubusercontent.com/6502474/105566231-0e368c00-5cf9-11eb-9fa9-a3cff3062487.png)

This isn't a big deal of course, because the user could just put the desired value in the "Note/CC/PG Number" parameter.  But really to be consistent with the UI, the channel aftertouch value should come from the "Value" parameter.  And also this distinction becomes important for the momentary button functionality, because without using "Value", that causes "Momentary Pressed Value" to be basically ignored for Channel Aftertouch.  The expected behavior should be that pressing the momentary button would result in using "Momentary Pressed Value" for the momentary event.

Anyway, I think the best way to address this is to harmonize mindi_ports enum and struct with the .ttl UI description, by renaming DATA1, DATA2, DATA2B to be NOTE_CC_PG, VALUE, VALUE_MOMENTARY respectively in the .h and .c file.  And then take care to use VALUE and VALUE_MOMENTARY for channel pressure/aftertouch messages in midirun.

I will include this fix as a separate commit in my upcoming PR.

**Comment by ericfont** [comment]
(actually I won't use underscore)

**Comment by ssj71** [comment]
Probably a bit potato potahto here, I was thinking more that DATA1 is simply the 2nd byte in the midi message. However I can't really argue with the user perspective you present as well as the shortcoming in the momentary button operation. Thanks for foreseeing that and I'll be happy to merge your change.

**Comment by ericfont** [comment]
the change is in https://github.com/ssj71/infamousPlugins/pull/46

**Comment by ssj71** [comment]
thanks for the PR
