### ISSUE TITLE
Infamous Plug-ins fail to load in Ardour 6.5

### ISSUE THREAD

**Issue by unfa** [ssj71/infamousPlugins#47]
Trying to add a plug-in to the processor box shows and error dialog:

```
The plugin "the infamous power cut" could not be loaded
See the Log window for more details (maybe)
```

I didn't find any extra info in the window though.

Can someone confirm this?

**Comment by trebmuh** [comment]
It's working here (LibraZiK-3) with Ardour 6.5 and Infamous plugins 0.3.0.

**Comment by unfa** [comment]
Hmm. Weird.
I'll see if I can provide some more details.

**Comment by ssj71** [comment]
Any update? I haven't updated ardour for quite some time since I've been a bit out of the LA world.

**Comment by agittins** [comment]
Working OK for me in Ardour 6.8.0 (debian sid using 5:0.3.0-1kxstudio2)
