### ISSUE TITLE
Please clarify in README where the ntk dependency should be sourced from

### ISSUE THREAD

**Issue by yurivict** [ssj71/infamousPlugins#48]
In FreeBSD it uses https://github.com/original-male/ntk but as of a few days ago this project has been deleted.

Please clarify what is the URL of upstream for ```ntk```.

The other potential upstream https://non.tuxfamily.org/wiki/NTK doesn't have a valid git URL git://git.tuxfamily.org/gitroot/non/fltk.git (```fatal: remote error: access denied or repository not exported: /gitroot/non/fltk.git```).

Thanks,
Yuri

**Comment by ssj71** [comment]
It appears the developer of the project removed all availability of his code. He recently had a very public disagreement with some packagers and list maintainers who had forked his project and I expect this is his retailiation. I'll see if I can find out whether he intends to make it available again in the future.

**Comment by ftoledo** [comment]
Are you thinking of stopping using that library and changing it for another? 
I just working on debian package.

**Comment by yurivict** [comment]
AAMOF, ntk source tarball is here: https://git.kx.studio/non/ntk/archive/v1.3.1001.tar.gz

There is no need to change to another library.

**Comment by ftoledo** [comment]
Thanks!

**Comment by ssj71** [comment]
Thanks indeed!
