### ISSUE TITLE
What version of lv2 is required ?

### ISSUE THREAD

**Issue by sc3sc3** [ssj71/infamousPlugins#50]
I get the following compile error
**_[ 10%] Building CXX object src/casynth/CMakeFiles/casynth_ui.dir/casynth_ui_main.cxx.o
/home/asdf/git/infamousPlugins/src/casynth/casynth_ui_main.cxx:13:49: error: using typedef-name ‘LV2UI_Descriptor’ after ‘struct’
   13 | static LV2UI_Handle init_casynthUI(const struct LV2UI_Descriptor * descriptor,
      |                                                 ^~~~~~~~~~~~~~~~
In file included from /home/asdf/git/infamousPlugins/build/src/casynth/casynth_ui.h:8,
                 from /home/asdf/git/infamousPlugins/src/casynth/casynth_ui_main.cxx:8:
/usr/local/lib/lv2/ui.lv2/ui.h:217:3: note: ‘LV2UI_Descriptor’ has a previous declaration here
  217 | } LV2UI_Descriptor;_**
According to some searches this could be related to lv2 version
I have version 1.16 installed
What version of lv2 is required ?
Thanks
Regards

**Comment by ssj71** [comment]
I have version 1.16 installed and it's compiling ok here. I'm not sure what's going on with your build.

**Comment by sc3sc3** [comment]
Ok thanks.
I don't know either :-)
